  name: rem
  version: '0.15.0'
  summary: rem is a small tool for remembering things on the command line.
  description: |
    rem is a small tool for remembering things on the command line. It can
    be used to store commands and execute them later on. Or to simply store
    lines of text.

  base: core20
  grade: stable
  confinement: classic

  architectures:  
    - build-on: i386
      run-on: i386
    - build-on: amd64
      run-on: amd64
    - build-on: armhf
      run-on: armhf
    - build-on: arm64
      run-on: arm64      

  apps:
    rem:
      command: bin/rem

  parts:
    rem:
      source: https://github.com/mborho/rem.git
      source-branch: master
      plugin: go
      go-buildtags: [core]
